name: "[CI]reflect branch update to master"
on:
  repository_dispatch:
    types: [bypass_test]

jobs:
  reflect_branch_update:
    env:
      VERSION: ${{ github.event.client_payload.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update
        run: |
          echo  $((`cat test.txt`+1)) > test.txt
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "test merge"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT_TOKEN }}
          branch: master
